import { cpSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import type { CreateKonektiOptions } from '../types';

import { createTierNote } from './prompt';
import { installDependencies } from './install';

function defaultRepoRoot(): string {
  return fileURLToPath(new URL('../../../../', import.meta.url));
}

function readRootPackageJson(repoRoot: string) {
  return JSON.parse(readFileSync(join(repoRoot, 'package.json'), 'utf8')) as {
    devDependencies: Record<string, string>;
    engines: { node: string };
    packageManager: string;
  };
}

function writeTextFile(filePath: string, content: string): void {
  mkdirSync(dirname(filePath), { recursive: true });
  writeFileSync(filePath, content, 'utf8');
}

function copyFrameworkSources(repoRoot: string, targetDirectory: string, orm: CreateKonektiOptions['orm']): void {
  const packageNames = ['core', 'config', 'di', 'module', 'http', 'jwt', 'passport', 'testing'] as string[];

  packageNames.push(orm === 'Prisma' ? 'prisma' : 'drizzle');

  for (const packageName of packageNames) {
    cpSync(join(repoRoot, 'packages', packageName), join(targetDirectory, 'packages', packageName), { recursive: true });
  }

  cpSync(join(repoRoot, 'tooling'), join(targetDirectory, 'tooling'), { recursive: true });
}

function createRootPackageJson(projectName: string, repoRoot: string): string {
  const rootPackage = readRootPackageJson(repoRoot);

  return JSON.stringify(
    {
      devDependencies: {
        ...rootPackage.devDependencies,
        tsx: '^4.20.4',
      },
      engines: rootPackage.engines,
      name: projectName,
      packageManager: rootPackage.packageManager,
      private: true,
      scripts: {
        build: "pnpm -r --if-present run build",
        dev: "pnpm --filter './apps/*' --if-present run dev",
        test: 'vitest run',
        'test:watch': 'vitest',
        typecheck: "tsc -p tsconfig.tools.json --noEmit && pnpm -r --if-present run typecheck",
      },
    },
    null,
    2,
  );
}

function createWorkspaceFile(): string {
  return ['packages:', '  - packages/*', '  - tooling/*', '  - apps/*', ''].join('\n');
}

function createRootVitestConfig(): string {
  return `import { defineConfig } from 'vitest/config';

import { konektiBabelDecoratorsPlugin } from './tooling/vite/src';

export default defineConfig({
  plugins: [konektiBabelDecoratorsPlugin()],
  test: {
    projects: [
      {
        extends: true,
        test: {
          name: 'packages',
          include: ['packages/**/*.test.ts'],
        },
      },
      {
        extends: true,
        test: {
          name: 'apps',
          include: ['apps/**/*.test.ts'],
        },
      },
    ],
    environment: 'node',
  },
});
`;
}

function createRootReadme(projectName: string, orm: CreateKonektiOptions['orm'], database: CreateKonektiOptions['database']): string {
  return `# ${projectName}

Generated by create-konekti.

- ORM: ${orm}
- Database: ${database}
- CORS: configurable through CORS_ORIGIN and scaffolded middleware
- Tx-aware repository example: src/examples/user.repo.ts
- Runtime path: bootstrapApplication -> handler mapping -> dispatcher -> middleware -> guard -> interceptor -> controller
`;
}

function createAppPackageJson(projectName: string, orm: CreateKonektiOptions['orm']): string {
  return JSON.stringify(
    {
      dependencies: {
        '@konekti/core': 'workspace:*',
        '@konekti/http': 'workspace:*',
        '@konekti/jwt': 'workspace:*',
        '@konekti/passport': 'workspace:*',
        '@konekti/testing': 'workspace:*',
        '@konekti-internal/module': 'workspace:*',
        ...(orm === 'Prisma' ? { '@konekti/prisma': 'workspace:*' } : { '@konekti/drizzle': 'workspace:*' }),
      },
      name: projectName,
      private: true,
      scripts: {
        build:
          "pnpm exec babel src --extensions .ts --ignore 'src/**/*.test.ts' --out-dir dist --config-file ../../tooling/babel/babel.config.cjs && pnpm exec tsc -p tsconfig.build.json",
        dev: 'pnpm exec tsx src/main.ts',
        test: 'pnpm exec vitest run',
        typecheck: 'pnpm exec tsc -p tsconfig.json --noEmit',
      },
      type: 'module',
      version: '0.0.0',
    },
    null,
    2,
  );
}

function createAppTsconfig(): string {
  return `{
  "extends": "../../tsconfig.base.json",
  "compilerOptions": {
    "rootDir": "src",
    "types": ["node"]
  },
  "include": ["src/**/*.ts"]
}
`;
}

function createAppTsconfigBuild(): string {
  return `{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "declaration": true,
    "declarationMap": true,
    "emitDeclarationOnly": false,
    "outDir": "dist"
  },
  "exclude": ["src/**/*.test.ts"]
}
`;
}

function createAppVitestConfig(): string {
  return `import { defineConfig } from 'vitest/config';

import { konektiBabelDecoratorsPlugin } from '../../tooling/vite/src';

export default defineConfig({
  plugins: [konektiBabelDecoratorsPlugin()],
  test: {
    environment: 'node',
    include: ['src/**/*.test.ts'],
  },
});
`;
}

function createAppViteConfig(): string {
  return `import { defineConfig } from 'vite';

import { konektiBabelDecoratorsPlugin } from '../../tooling/vite/src';

export default defineConfig({
  plugins: [konektiBabelDecoratorsPlugin()],
});
`;
}

function createNodeAdapterFile(): string {
  return `import { createServer } from 'node:http';
import { URL } from 'node:url';

import type { Dispatcher, FrameworkRequest, FrameworkResponse, HttpApplicationAdapter } from '@konekti/http';

function createFrameworkResponse(response: import('node:http').ServerResponse): FrameworkResponse {
  return {
    committed: response.headersSent || response.writableEnded,
    headers: {},
    redirect(status, location) {
      this.setStatus(status);
      this.setHeader('Location', location);
      void this.send(undefined);
    },
    send(body) {
      if (response.writableEnded) {
        this.committed = true;
        return;
      }

      if (!response.hasHeader('Content-Type')) {
        response.setHeader('Content-Type', 'application/json; charset=utf-8');
      }

      response.end(body === undefined ? '' : JSON.stringify(body));
      this.committed = true;
    },
    setHeader(name, value) {
      this.headers[name] = value;
      response.setHeader(name, value);
    },
    setStatus(code) {
      response.statusCode = code;
      this.statusCode = code;
    },
    statusCode: response.statusCode,
  };
}

async function createFrameworkRequest(request: import('node:http').IncomingMessage): Promise<FrameworkRequest> {
  const controller = new AbortController();
  const chunks: Buffer[] = [];

  request.on('aborted', () => {
    controller.abort(new Error('Request stream aborted.'));
  });

  request.on('close', () => {
    if (!request.complete) {
      controller.abort(new Error('Request stream closed before completion.'));
    }
  });

  for await (const chunk of request) {
    chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk));
  }

  const bodyText = Buffer.concat(chunks).toString('utf8');
  const url = new URL(request.url ?? '/', 'http://' + (request.headers.host ?? 'localhost'));

  return {
    body: bodyText ? JSON.parse(bodyText) : undefined,
    cookies: {},
    headers: request.headers as Record<string, string | string[] | undefined>,
    method: request.method ?? 'GET',
    params: {},
    path: url.pathname,
    query: Object.fromEntries(url.searchParams.entries()),
    raw: request,
    signal: controller.signal,
    url: request.url ?? url.pathname,
  };
}

export class NodeHttpAdapter implements HttpApplicationAdapter {
  private server?: import('node:http').Server;

  constructor(private readonly port: number) {}

  async listen(dispatcher: Dispatcher): Promise<void> {
    this.server = createServer(async (request, response) => {
      const frameworkRequest = await createFrameworkRequest(request);
      const frameworkResponse = createFrameworkResponse(response);

      await dispatcher.dispatch(frameworkRequest, frameworkResponse);
    });

    await new Promise<void>((resolve) => {
      this.server?.listen(this.port, resolve);
    });
  }

  async close(): Promise<void> {
    if (!this.server) {
      return;
    }

    await new Promise<void>((resolve, reject) => {
      this.server?.close((error) => {
        if (error) {
          reject(error);
          return;
        }

        resolve();
      });
    });
  }
}
`;
}

function createAppFile(projectName: string): string {
  return `import { fileURLToPath } from 'node:url';

 import { Global, Inject, Module } from '@konekti/core';
 import { bootstrapApplication } from '@konekti-internal/module';
 import { Controller, Get, createCorsMiddleware, type GuardContext } from '@konekti/http';
import { DefaultJwtVerifier, JwtExpiredTokenError, JwtInvalidTokenError, createJwtCoreProviders } from '@konekti/jwt';
import {
  AuthenticationExpiredError,
  AuthenticationFailedError,
  AuthenticationRequiredError,
  RequireScopes,
  UseAuth,
  createPassportProviders,
  type AuthStrategy,
} from '@konekti/passport';

import { HealthResponseDto } from './dto/health.dto';
import { HealthRepo } from './health.repo';
import { HealthService } from './health.service';
import { NodeHttpAdapter } from './node-http-adapter';

function extractBearerToken(value: string | string[] | undefined): string | undefined {
  const authorization = Array.isArray(value) ? value[0] : value;

  if (!authorization) {
    return undefined;
  }

  const [scheme, token] = authorization.split(' ');

  if (scheme !== 'Bearer' || !token) {
    return undefined;
  }

  return token;
}

@Inject([DefaultJwtVerifier])
class LocalJwtStrategy implements AuthStrategy {
  constructor(private readonly verifier: DefaultJwtVerifier) {}

  async authenticate(context: GuardContext) {
    const token = extractBearerToken(context.requestContext.request.headers.authorization);

    if (!token) {
      throw new AuthenticationRequiredError();
    }

    try {
      return await this.verifier.verifyAccessToken(token);
    } catch (error) {
      if (error instanceof JwtExpiredTokenError) {
        throw new AuthenticationExpiredError();
      }

      if (error instanceof JwtInvalidTokenError) {
        throw new AuthenticationFailedError();
      }

      throw error;
    }
  }
}

@Inject([HealthService])
@Controller('/health')
class HealthController {
  constructor(private readonly healthService: HealthService) {}

  @Get('/')
  getHealth(): HealthResponseDto {
    return this.healthService.getHealth();
  }

  @Get('/profile')
  @RequireScopes('profile:read')
  @UseAuth('jwt')
  getProfile(_input: unknown, context: { principal?: { subject: string } }) {
    return { subject: context.principal?.subject };
  }
}
@Global()
@Module({
  controllers: [HealthController],
  providers: [
    HealthRepo,
    HealthService,
    ...createJwtCoreProviders({
      algorithms: ['HS256'],
      audience: '${projectName}',
      issuer: '${projectName}',
      secret: process.env.JWT_SECRET ?? 'starter-secret',
    }),
    LocalJwtStrategy,
    ...createPassportProviders(
      {
        defaultStrategy: 'jwt',
      },
      [{ name: 'jwt', token: LocalJwtStrategy }],
    ),
  ],
})
class AppModule {}

export async function createApp(mode: 'dev' | 'prod' | 'test', adapter?: NodeHttpAdapter) {
  const cwd = fileURLToPath(new URL('..', import.meta.url));
  const corsOrigin = process.env.CORS_ORIGIN ?? '*';

  return bootstrapApplication({
    adapter,
    cwd,
    middleware: [
      createCorsMiddleware({
        allowHeaders: ['Authorization', 'Content-Type'],
        allowOrigin: corsOrigin === '*' ? '*' : corsOrigin.split(',').map((value) => value.trim()).filter(Boolean),
        exposeHeaders: ['X-Request-Id'],
      }),
    ],
    mode,
    rootModule: AppModule,
  });
}
`;
}

function createHealthRepoFile(projectName: string, _orm: CreateKonektiOptions['orm']): string {
  return `import type { HealthResponseDto } from './dto/health.dto';

export class HealthRepo {
  findHealth(): HealthResponseDto {
    return {
      ok: true,
      service: '${projectName}',
    };
  }
}
`;
}

function createHealthServiceFile(): string {
  return `import { Inject } from '@konekti/core';
import type { HealthResponseDto } from './dto/health.dto';

import { HealthRepo } from './health.repo';

@Inject([HealthRepo])
export class HealthService {
  constructor(private readonly healthRepo: HealthRepo) {}

  getHealth(): HealthResponseDto {
    return this.healthRepo.findHealth();
  }
}
`;
}

function createHealthDtoFile(): string {
  return `export class HealthResponseDto {
  ok!: boolean;
  service!: string;
}
`;
}

function createOrmRepositoryExampleFile(orm: CreateKonektiOptions['orm']): string {
  if (orm === 'Prisma') {
    return `import { Inject } from '@konekti/core';
import type { PrismaClientLike } from '@konekti/prisma';
import { PrismaService } from '@konekti/prisma';

type UserRecord = {
  email: string;
  id: string;
};

type UserPrismaClient = PrismaClientLike<{
  user: {
    findMany(): Promise<UserRecord[]>;
  };
}> & {
  user: {
    findMany(): Promise<UserRecord[]>;
  };
};

@Inject([PrismaService])
export class UserRepo {
  constructor(private readonly prisma: PrismaService<UserPrismaClient>) {}

  async listUsers(): Promise<UserRecord[]> {
    const current = this.prisma.current();

    return current.user.findMany();
  }
}
`;
  }

  return `import { Inject } from '@konekti/core';
import { DrizzleDatabase } from '@konekti/drizzle';

type UserRecord = {
  email: string;
  id: string;
};

@Inject([DrizzleDatabase])
export class UserRepo {
  constructor(
    private readonly database: DrizzleDatabase<{
      users: {
        findMany(): Promise<UserRecord[]>;
      };
    }>,
  ) {}

  async listUsers(): Promise<UserRecord[]> {
    const current = this.database.current();

    return current.users.findMany();
  }
}
`;
}

function createMainFile(): string {
  return `import { createApp } from './app';
import { NodeHttpAdapter } from './node-http-adapter';

const port = Number(process.env.PORT ?? 3000);
const app = await createApp('dev', new NodeHttpAdapter(port));

await app.listen();
`;
}

function createAppTestFile(projectName: string): string {
  return `import { createHmac } from 'node:crypto';

import { describe, expect, it } from 'vitest';

import type { FrameworkRequest, FrameworkResponse } from '@konekti/http';

import { createApp } from './app';

function encodeBase64Url(value: string): string {
  return Buffer.from(value, 'utf8')
    .toString('base64')
    .replace(/=/g, '')
    .replace(/\\+/g, '-')
    .replace(/\\//g, '_');
}

function signToken(payload: Record<string, unknown>, secret: string) {
  const headerSegment = encodeBase64Url(JSON.stringify({ alg: 'HS256', typ: 'JWT' }));
  const payloadSegment = encodeBase64Url(JSON.stringify(payload));
  const signature = createHmac('sha256', secret)
    .update(headerSegment + '.' + payloadSegment)
    .digest('base64')
    .replace(/=/g, '')
    .replace(/\\+/g, '-')
    .replace(/\\//g, '_');

  return headerSegment + '.' + payloadSegment + '.' + signature;
}

function createRequest(path: string, authorization?: string): FrameworkRequest {
  return {
    body: undefined,
    cookies: {},
    headers: authorization ? { authorization } : {},
    method: 'GET',
    params: {},
    path,
    query: {},
    raw: {},
    url: path,
  };
}

function createResponse(): FrameworkResponse & { body?: unknown } {
  return {
    committed: false,
    headers: {},
    redirect(status, location) {
      this.setStatus(status);
      this.setHeader('Location', location);
      this.committed = true;
    },
    send(body) {
      this.body = body;
      this.committed = true;
    },
    setHeader(name, value) {
      this.headers[name] = value;
    },
    setStatus(code) {
      this.statusCode = code;
    },
    statusCode: 200,
  };
}

describe('generated app', () => {
  it('dispatches the health route through the runtime path', async () => {
    const app = await createApp('test');
    const response = createResponse();

    await app.dispatch(createRequest('/health'), response);

    expect(response.body).toEqual({ ok: true, service: '${projectName}' });

    await app.close();
  });

  it('stores a verified principal for the protected profile route', async () => {
    const app = await createApp('test');
    const response = createResponse();
    const token = signToken(
      {
        aud: '${projectName}',
        exp: Math.floor(Date.now() / 1000) + 60,
        iss: '${projectName}',
        scope: 'profile:read',
        sub: 'starter-user',
      },
      'starter-secret',
    );

    await app.dispatch(createRequest('/health/profile', 'Bearer ' + token), response);

    expect(response.body).toEqual({ subject: 'starter-user' });

    await app.close();
  });
});
`;
}

function createEnvFile(secret: string): string {
  return `JWT_SECRET=${secret}
CORS_ORIGIN=*
PORT=3000
`;
}

function scaffoldAppPackage(targetDirectory: string, options: CreateKonektiOptions): void {
  const appDirectory = join(targetDirectory, 'apps', options.projectName);

  writeTextFile(join(appDirectory, 'package.json'), createAppPackageJson(options.projectName, options.orm));
  writeTextFile(join(appDirectory, 'tsconfig.json'), createAppTsconfig());
  writeTextFile(join(appDirectory, 'tsconfig.build.json'), createAppTsconfigBuild());
  writeTextFile(join(appDirectory, 'vite.config.ts'), createAppViteConfig());
  writeTextFile(join(appDirectory, 'vitest.config.ts'), createAppVitestConfig());
  writeTextFile(join(appDirectory, '.env.dev'), createEnvFile('starter-secret'));
  writeTextFile(join(appDirectory, '.env.test'), createEnvFile('starter-secret'));
  writeTextFile(join(appDirectory, '.env.prod'), createEnvFile('starter-secret'));
  writeTextFile(join(appDirectory, 'src/app.ts'), createAppFile(options.projectName));
  writeTextFile(join(appDirectory, 'src/main.ts'), createMainFile());
  writeTextFile(join(appDirectory, 'src/node-http-adapter.ts'), createNodeAdapterFile());
  writeTextFile(join(appDirectory, 'src/health.repo.ts'), createHealthRepoFile(options.projectName, options.orm));
  writeTextFile(join(appDirectory, 'src/health.service.ts'), createHealthServiceFile());
  writeTextFile(join(appDirectory, 'src/dto/health.dto.ts'), createHealthDtoFile());
  writeTextFile(join(appDirectory, 'src/examples/user.repo.ts'), createOrmRepositoryExampleFile(options.orm));
  writeTextFile(join(appDirectory, 'src/app.test.ts'), createAppTestFile(options.projectName));
}

export async function scaffoldKonektiApp(options: CreateKonektiOptions): Promise<void> {
  const repoRoot = options.repoRoot ? resolve(options.repoRoot) : defaultRepoRoot();
  const targetDirectory = resolve(options.targetDirectory);

  mkdirSync(targetDirectory, { recursive: true });
  copyFrameworkSources(repoRoot, targetDirectory, options.orm);
  writeTextFile(join(targetDirectory, 'package.json'), createRootPackageJson(options.projectName, repoRoot));
  writeTextFile(join(targetDirectory, 'pnpm-workspace.yaml'), createWorkspaceFile());
  writeTextFile(join(targetDirectory, 'tsconfig.base.json'), readFileSync(join(repoRoot, 'tsconfig.base.json'), 'utf8'));
  writeTextFile(join(targetDirectory, 'tsconfig.tools.json'), readFileSync(join(repoRoot, 'tsconfig.tools.json'), 'utf8'));
  writeTextFile(join(targetDirectory, 'vite.config.ts'), readFileSync(join(repoRoot, 'vite.config.ts'), 'utf8'));
  writeTextFile(join(targetDirectory, 'vitest.config.ts'), createRootVitestConfig());
  writeTextFile(
    join(targetDirectory, 'README.md'),
    `${createRootReadme(options.projectName, options.orm, options.database)}\n\n${createTierNote(options.orm, options.database)}\n`,
  );
  scaffoldAppPackage(targetDirectory, options);

  if (!options.skipInstall) {
    await installDependencies(targetDirectory, options.packageManager);
  }
}
