import { Buffer } from 'node:buffer';

import nodemailer from 'nodemailer';
import type Mail from 'nodemailer/lib/mailer';
import type SMTPTransport from 'nodemailer/lib/smtp-transport';

import type {
  EmailAttachment,
  EmailTransport,
  EmailTransportContext,
  EmailTransportFactory,
  EmailTransportReceipt,
  NormalizedEmailMessage,
} from '../types.js';

/** Node-only Nodemailer transporter type used by the explicit `@konekti/email/node` seam. */
export type NodemailerTransporter = Mail<SMTPTransport.SentMessageInfo>;

/**
 * Options for wrapping an existing Nodemailer transporter without transferring resource ownership.
 *
 * @remarks
 * Use this when your application already constructs and manages the Nodemailer transporter
 * at the Node boundary, but you still want to satisfy the shared {@link EmailTransport}
 * contract consumed by `@konekti/email`.
 */
export interface NodemailerEmailTransportOptions {
  /** Existing Nodemailer transporter instance that remains owned by the caller. */
  transporter: NodemailerTransporter;
}

/**
 * Options for creating a factory-owned SMTP transporter behind `@konekti/email/node`.
 *
 * @remarks
 * The resulting factory advertises `ownsResources: true`, allowing the shared email module
 * to close the Nodemailer transporter during application shutdown while keeping that behavior
 * isolated to the Node-only subpath.
 */
export interface NodemailerEmailTransportFactoryOptions {
  /** Optional diagnostic label surfaced through the root email status snapshot. */
  kind?: string;

  /** SMTP connection settings or SMTP URL passed directly to `nodemailer.createTransport(...)`. */
  smtp: SMTPTransport.Options | string;
}

function createAddress(address: { address: string; name?: string }): string {
  return address.name ? `${address.name} <${address.address}>` : address.address;
}

function createAddressList(addresses: readonly { address: string; name?: string }[]): string[] | undefined {
  if (addresses.length === 0) {
    return undefined;
  }

  return addresses.map((address) => createAddress(address));
}

function createAttachments(attachments: readonly EmailAttachment[] | undefined): Mail.Attachment[] | undefined {
  if (!attachments || attachments.length === 0) {
    return undefined;
  }

  return attachments.map((attachment) => ({
    content:
      typeof attachment.content === 'string'
        ? attachment.content
        : Buffer.from(attachment.content.buffer, attachment.content.byteOffset, attachment.content.byteLength),
    contentType: attachment.contentType,
    filename: attachment.filename,
  }));
}

function createSendMailOptions(message: NormalizedEmailMessage): Mail.Options {
  return {
    attachments: createAttachments(message.attachments),
    bcc: createAddressList(message.bcc),
    cc: createAddressList(message.cc),
    from: createAddress(message.from),
    headers: message.headers,
    html: message.html,
    replyTo: createAddressList(message.replyTo),
    subject: message.subject,
    text: message.text,
    to: createAddressList(message.to),
  };
}

function normalizeAddressList(value: unknown): string[] {
  if (!Array.isArray(value)) {
    return [];
  }

  return value.map((entry) => String(entry));
}

/**
 * Node-only {@link EmailTransport} adapter that forwards normalized email messages to Nodemailer.
 *
 * @remarks
 * This adapter intentionally lives behind `@konekti/email/node` so SMTP/Nodemailer behavior,
 * verification, and connection cleanup never leak into the transport-agnostic root barrel.
 */
export class NodemailerEmailTransport implements EmailTransport {
  constructor(private readonly transporter: NodemailerTransporter) {}

  /**
   * Sends one normalized email message through the wrapped Nodemailer transporter.
   *
   * @param message Normalized message generated by the shared email package before provider hand-off.
   * @param _context Optional transport context accepted for contract compatibility with the shared root API.
   * @returns A normalized receipt containing accepted/rejected recipients, response details, and message id.
   *
   * @example
   * ```ts
   * const transport = createNodemailerEmailTransport({ transporter });
   * await transport.send(message, {});
   * ```
   */
  async send(message: NormalizedEmailMessage, _context: EmailTransportContext): Promise<EmailTransportReceipt> {
    const receipt = await this.transporter.sendMail(createSendMailOptions(message));

    return {
      accepted: normalizeAddressList(receipt.accepted),
      messageId: typeof receipt.messageId === 'string' ? receipt.messageId : undefined,
      metadata: receipt.envelope ? { envelope: receipt.envelope } : undefined,
      pending: normalizeAddressList(receipt.pending),
      rejected: normalizeAddressList(receipt.rejected),
      response: typeof receipt.response === 'string' ? receipt.response : undefined,
    };
  }

  /**
   * Verifies SMTP connectivity and authentication through the wrapped Nodemailer transporter.
   *
   * @returns A promise that resolves once Nodemailer reports the transporter is ready.
   */
  async verify(): Promise<void> {
    await this.transporter.verify();
  }

  /**
   * Closes the wrapped Nodemailer transporter.
   *
   * @returns A promise that resolves after the close signal has been forwarded.
   */
  async close(): Promise<void> {
    this.transporter.close();
  }
}

/**
 * Wraps an existing Nodemailer transporter as an `EmailTransport` without transferring ownership.
 *
 * @param options Existing transporter wiring owned by the caller.
 * @returns A Node-only transport implementation that can be passed directly to `EmailModule.forRoot(...)`.
 *
 * @example
 * ```ts
 * const transporter = nodemailer.createTransport({ host: 'smtp.example.com', port: 587, secure: false });
 * const transport = createNodemailerEmailTransport({ transporter });
 * ```
 */
export function createNodemailerEmailTransport(options: NodemailerEmailTransportOptions): EmailTransport {
  return new NodemailerEmailTransport(options.transporter);
}

/**
 * Creates a factory-owned Nodemailer SMTP transport for the explicit `@konekti/email/node` entrypoint.
 *
 * @param options SMTP connection settings and an optional diagnostic label.
 * @returns An {@link EmailTransportFactory} that lazily creates a Nodemailer transport and marks ownership as internal.
 *
 * @example
 * ```ts
 * EmailModule.forRoot({
 *   transport: createNodemailerEmailTransportFactory({
 *     smtp: {
 *       auth: { pass: 'secret', user: 'mailer' },
 *       host: 'smtp.example.com',
 *       port: 587,
 *       secure: false,
 *     },
 *   }),
 *   verifyOnModuleInit: true,
 * });
 * ```
 */
export function createNodemailerEmailTransportFactory(
  options: NodemailerEmailTransportFactoryOptions,
): EmailTransportFactory {
  const kind = options.kind?.trim() || 'nodemailer-smtp';

  return {
    create: async () => new NodemailerEmailTransport(nodemailer.createTransport(options.smtp)),
    kind,
    ownsResources: true,
  };
}
